### ISSUE TITLE
Backport HIVE-20192

### ISSUE THREAD

**Issue by PACordonnier** [TOSIT-IO/hive#12]
https://issues.apache.org/jira/browse/HIVE-20192

Issue has been backported to Hive 3.2 and I would like it to be backported to 3.1 as well

**Comment by Pierrotws** [comment]
Can you review PR #17 and confirm it solves your issue ?

**Comment by PACordonnier** [comment]
Fix is included in current 3.1.3-2.0-SNAPSHOT
