### ISSUE TITLE
Hive1: rename branch 1 

### ISSUE THREAD

**Issue by PACordonnier** [TOSIT-IO/hive#19]
Relates to https://github.com/TOSIT-IO/TDP/pull/90

**Comment by PACordonnier** [comment]
Done. Branch branch-1.2-TDP has been renamed to branch-1.2.3-TDP

**Comment by rpignolet** [comment]
`branch-1.2.3-TDP` does not exist but I see a new `branch-1.2.2-TDP`

**Comment by PACordonnier** [comment]
It was a mistake. I renamed `branch-1.2.2-TDP` to `branch-1.2.3-TDP`. Thank you for noticing

**Comment by rpignolet** [comment]
Nice, but in the new `branch-1.2.3-TDP`, readme say `1.2.2`, the apache readme is not updated ?

**Comment by PACordonnier** [comment]
No it is not, probably why I made the mistake. 1.2.3 was never released by apache
