### ISSUE TITLE
Build fails due to conjars repo being down

### ISSUE THREAD

**Issue by PACordonnier** [TOSIT-IO/hive#4]
I've started building "hive 2-3" which fails due to a Conjars repo being down.

Obviously it can work on your machine if your current `~/.m2/repository` contains needed jars.

I don't understand how previous builds worked since conjar seems to be down since march 2021, see announcement here

https://groups.google.com/g/cascading-user/c/qAQvajapawI

More info on how to fix here https://conjars.wensel.net/

**Comment by Pierrotws** [comment]
solved with wikimedia repo
