### ISSUE TITLE
pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar dependency can't be download

### ISSUE THREAD

**Issue by PACordonnier** [TOSIT-IO/hive#6]
On branch `branch 2.3-TDP`, the dependency `pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar` can't be downloaded.

I think it used to be able to be pulled from conjar but now fails even with the mirror see #4 and #5

I found discussions about this dependency (which is a transitive dependency from Calcite) https://issues.apache.org/jira/browse/HIVE-25173 

I found no workaround but to manually place the jar in my `~/.m2/repository`. I've downloaded the jar here https://repository.mapr.com/nexus/content/groups/mapr-public/conjars/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/

We can maybe add this mapr repository as a base repo in the parent `pom.xml`

**Comment by Pierrotws** [comment]
pentaho aggdesigner has been excluded from build
